[package]
name = "git_example"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser.d.hutchison@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
